apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: vibe-social
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: vibe-social.westeurope.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: documentation
                port:
                  number: 80
          - path: /event-tracking(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: event-tracking
                port:
                  number: 80
          - path: /event-tracking-grpc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: event-tracking
                port:
                  number: 81
          - path: /location-discovery(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: location-discovery
                port:
                  number: 80
          - path: /backend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /payment-webhooks(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: payment-webhooks
                port:
                  number: 80
