apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: vibe-social
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: event-tracking
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /event-tracking
            pathType: Prefix
            backend:
              service:
                name: event-tracking
                port:
                  number: 80
