apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: vibe-social
spec:
  version: 8.11.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  cpu: "1.0"
                  memory: "1024Mi"
                requests:
                  cpu: "0.1"
                  memory: "1024Mi"
